# -*- mode: ruby -*-
# vi: set ft=ruby :

# ==> Set this to your 42 login (lowercase, no spaces)
LOGIN = "kel-baam"

BOX     = "debian/bookworm64"
SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.box = BOX

  config.vm.define "#{LOGIN}S" do |server|
    server.vm.hostname = "#{LOGIN}S"

    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |vb|
      vb.name   = "#{LOGIN}S"
      vb.memory = 2048
      vb.cpus   = 2
    end

    # sync the confs/ folder so kubectl apply can read the manifests
    server.vm.synced_folder "confs", "/vagrant/confs"

    server.vm.provision "shell", path: "scripts/server.sh", args: [SERVER_IP]
  end
end